### ISSUE TITLE
Callback code (for Slack for example)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/deployrjs#5]
Can we add a callback so that we can choose which channel it will create a message for on success or fail at least of a deploy?

"{$branch} successfully deployed to project."

**Comment by tushar-singh** [comment]
implemented as an addon which is completely separate from deployr, since actual build logic is entirely out of deployrjs (which is a good thing)

```javascript
const Slack = require('deployrjs/addons/slack')('YOUR_SLACK_HOOK_URL');

deployment.listen((action, pull) => {
    Slack.post('Starting deployment...');

    pull().then(() => exec('npm run build')).then(() => {
        Slack.post('Deployed! :D')
    })
});
```
